### ISSUE TITLE
Could you share the config.yaml file used in home assistant?

### ISSUE THREAD

**Issue by scarletwiz** [RomLab/esp32-local-thermostat#1]
Hello. I am a developer who has been greatly benefiting from your project. I am very pleased to have obtained valuable information. If possible, could you kindly share the config.yaml file used in home assistant? I am facing some challenges while configuring home assistant, and your assistance would be highly appreciated. Thank you in advance.

**Comment by RomLab** [comment]
Hello, Here is all configuration for HomeAssistant: https://github.com/RomLab/home-assistant-for-underfloor-heating-docker-v2.0
